### ISSUE TITLE
How to pass the parameter processingInstanceType to the dataprocessing command? 

### ISSUE THREAD

**Issue by AWS-Bassem** [aws/graph-notebook#103]
How do you pass the parameter [processingInstanceType ](https://docs.aws.amazon.com/neptune/latest/userguide/machine-learning-api-dataprocessing.html) when using the %neptune-ml magic dataprocessing command to start a processing job?

The [Notebooks ](https://github.com/aws/graph-notebook/tree/main/src/graph_notebook/notebooks/04-Machine-Learning)  only have the below code which does not have this parameter.
```
processing_params = f"""
--config-file-name training-job-configuration.json
--job-id {training_job_name} 
--s3-input-uri {export_results['outputS3Uri']} 
--s3-processed-uri {str(s3_bucket_uri)}/preloading """
```

```
%neptune_ml dataprocessing start --wait --store-to processing_results {processing_params}
```

**Comment by austinkline** [comment]
Thanks for creating this @AWS-Bassem, we should just be able to add this parameter to the dataprocessing variant of neptune_ml. 

linking the sub parser that we use for those parameters for future reference when we pick this up:
https://github.com/aws/graph-notebook/blob/main/src/graph_notebook/magics/ml.py#L64

**Comment by michaelnchin** [comment]
Hi @AWS-Bassem, 

Support for `processingInstanceType` has been added in #202; you can now pass in this parameter by specifying the `--instance-type` option.

Closing out this issue as the requested feature has been completed; please feel free to re-open if there are any further questions or concerns.
