### ISSUE TITLE
[BUG] Summarize the issue in a few words here

### ISSUE THREAD

**Issue by israelio** [aws/graph-notebook#129]
**Describe the bug**
With ver 2.1.3 nbextention not found while running  jupyter nbextension install --py --sys-prefix graph_notebook.widgets
Everything works fine with ver 2.1.2

jupyter nbextension install --py --sys-prefix graph_notebook.widgets:
#10 1.000 Installing /usr/local/lib/python3.6/site-packages/graph_notebook/widgets/nbextension/static -> graph_notebook_widgets
#10 1.003 Traceback (most recent call last):
#10 1.003   File "/usr/local/bin/jupyter-nbextension", line 8, in <module>
#10 1.003     sys.exit(main())
#10 1.003   File "/usr/local/lib/python3.6/site-packages/jupyter_core/application.py", line 254, in launch_instance
#10 1.003     return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
#10 1.003   File "/usr/local/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
#10 1.003     app.start()
#10 1.003   File "/usr/local/lib/python3.6/site-packages/notebook/nbextensions.py", line 988, in start
#10 1.003     super(NBExtensionApp, self).start()
#10 1.003   File "/usr/local/lib/python3.6/site-packages/jupyter_core/application.py", line 243, in start
#10 1.003     self.subapp.start()
#10 1.003   File "/usr/local/lib/python3.6/site-packages/notebook/nbextensions.py", line 716, in start
#10 1.003     self.install_extensions()
#10 1.003   File "/usr/local/lib/python3.6/site-packages/notebook/nbextensions.py", line 695, in install_extensions
#10 1.003     **kwargs
#10 1.003   File "/usr/local/lib/python3.6/site-packages/notebook/nbextensions.py", line 225, in install_nbextension_python
#10 1.003     destination=dest, logger=logger
#10 1.003   File "/usr/local/lib/python3.6/site-packages/notebook/nbextensions.py", line 199, in install_nbextension
#10 1.003     _maybe_copy(src, full_dest, logger=logger)
#10 1.003   File "/usr/local/lib/python3.6/site-packages/notebook/nbextensions.py", line 1043, in _maybe_copy
#10 1.003     if _should_copy(src, dest, logger=logger):
#10 1.003   File "/usr/local/lib/python3.6/site-packages/notebook/nbextensions.py", line 1019, in _should_copy
#10 1.003     if os.stat(src).st_mtime - os.stat(dest).st_mtime > 1e-6:
#10 1.003 FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.6/site-packages/graph_notebook/widgets/nbextension/static'
------
executor failed running [/bin/sh -c jupyter nbextension install --py --sys-prefix graph_notebook.widgets]: exit code: 1

**To Reproduce**
Run the installation as described over here: https://pypi.org/project/graph-notebook/2.1.3/

# pin specific versions of Jupyter and Tornado dependency
pip install notebook==5.7.10
pip install tornado==4.5.3

# install the package
pip install graph-notebook

# install and enable the visualization widget
jupyter nbextension install --py --sys-prefix graph_notebook.widgets.  <--- fails

**Expected behavior**
To pass and install the extentions

**Desktop (please complete the following information):**
 - OS: python:3.6.13-slim docker image

**Additional context**
-

**Comment by michaelnchin** [comment]
Hi @israelio, thanks for the bug report!

I had a look at the 2.1.3 release wheel, and have identified the source of the bug. It appears that some of the files in the widgets directory were incorrectly generated for this build. 

A fix for this bug will be going out with release 2.1.4; I will notify you when this is completed.

**Comment by michaelnchin** [comment]
This is now fixed with release 2.1.4. @israelio, thank you again for reporting this bug! Please feel free to reopen this issue if you run into any further problems.
