### ISSUE TITLE
Error - Introduction to Link Prediction Gremlin

### ISSUE THREAD

**Issue by Roshin29** [aws/graph-notebook#145]
After running the training parameter

# The training_job_name can be set to a unique value below, otherwise one will be auto generated
training_job_name=neptune_ml.get_training_job_name('link-prediction-demo5')

processing_params = f"""
--config-file-name training-job-configuration.json
--job-id {training_job_name} 
--s3-input-uri {export_results['outputS3Uri']} 
--s3-processed-uri {str(s3_bucket_uri)}/preloading """

%neptune_ml dataprocessing start --wait --store-to processing_results {processing_params}

Then get the error after export is failed and the dat processing job failed

Wait called on dataprocessing job link-prediction-demo5-1626912168
Data processing is finished
{
  "id": "link-prediction-demo5-1626912168",
  "status": "Failed",
  "processingJobDefinition": {
    "name": "link-pre-preloading-2021-07-22-00-02-1360000",
    "arn": "arn:aws:sagemaker:eu-west-2:603516729577:processing-job/link-pre-preloading-2021-07-22-00-02-1360000",
    "status": "Failed",
    "outputLocation": "s3://iap-ai-tst-02-ml-neptune/preloading/link-pre-preloading-2021-07-22-00-02-1360000/preloading-output",
    "failureReason": "AlgorithmError: See job logs for more information",
    "cloudwatchLogUrl": "https://eu-west-2.console.aws.amazon.com/cloudwatch/home?region=eu-west-2#logStream:group=/aws/sagemaker/ProcessingJobs;prefix=link-pre-preloading-2021-07-22-00-02-1360000"
  }
}

**Comment by bechbd** [comment]
This has been resolved with the 3.0.0 release
