### ISSUE TITLE
Selecting layouts

### ISSUE THREAD

**Issue by gourav-sg** [aws/graph-notebook#193]
**Is your feature request related to a problem? Please describe.**
Can we please select different layouts that is so mandatory to make any sense of graphs

**Describe the solution you'd like**
the ability to select different layouts as shown here https://js.cytoscape.org/ 

**Describe alternatives you've considered**
Plotly, but the coding is too high

**Additional context**
Graph visualisations without layout and filtering becomes quite a lot of work particularly with large graphs.

**Comment by krlawrence** [comment]
Thanks for the feedback @gourav-sg . Under the covers the rendering today is performed using Vis.js. Any of the Vis.js settings can be changed using the `%%graph_notebook_vis_options` magic. There is an example of changing to a network layout in the `Air-Routes-Gremlin` sample notebook. That said, we are interested in making more of the visualizations available via the UI and/or options to the magic commands. There is a recent [pull request](https://github.com/aws/graph-notebook/pull/190) for example, that adds support for controlling the physics simulation duration.

**Comment by gourav-sg** [comment]
hi ,
@krlawrence  can you have a look at this https://blog.jupyter.org/interactive-graph-visualization-in-jupyter-with-ipycytoscape-a8828a54ab63? I think that cytoscape also does a brilliant work.

Regards,
Gourav

**Comment by joywa** [comment]
Hi @gourav-sg thank you for this enhancement request. We don't have plans to change from vis.js to cytoscape at this time for graph-notebook. However, have you seen the Graph Explorer project that was recently launched? https://github.com/aws/graph-explorer. It is actually built using Cytoscape and has preset layouts. Please give it a try and let us know if this can work for your use cases.

**Comment by gourav-sg** [comment]
Hi,

This sounds fantastic, thank you so much.

Regards,
Gourav

**Comment by gourav-sg** [comment]
Hi Gourav!

So great seeing that you have found the graph-explorer.

How is it going so far? I would love to hear about what you are building. Thank you for reaching out.

Cheers,

Denise

From: Gourav Sengupta ***@***.***>
Date: Thursday, January 19, 2023 at 4:08 AM
To: aws/graph-notebook ***@***.***>, "Gosnell, Denise" ***@***.***>
Subject: RE: [EXTERNAL][aws/graph-notebook] Selecting layouts (#193)


CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you can confirm the sender and know the content is safe.


Hi,

This sounds fantastic, thank you so much.

Regards,
Gourav
On Thu, 19 Jan 2023, 00:24 Joy Wang, ***@***.******@***.***>> wrote:

Hi @gourav-sg<https://github.com/gourav-sg> thank you for this enhancement request. We don't have plans to change from vis.js to cytoscape at this time for graph-notebook. However, have you seen the Graph Explorer project that was recently launched? https://github.com/aws/graph-explorer. It is actually built using Cytoscape and has preset layouts. Please give it a try and let us know if this can work for your use cases.
