### ISSUE TITLE
Blazegraph example has copied content from dbpedia example

### ISSUE THREAD

**Issue by ThomasThelen** [aws/graph-notebook#197]
**Describe the bug**
More of a minor documentation issue. The blazegraph database example has non-relevant information about dbpedia, most likely just a copy+paste error. 

**To Reproduce**
1. Go to the [blazegraph](https://github.com/aws/graph-notebook/tree/main/additional-databases/blazegraph) example
2. Note that it has mostly the same documentation as the [dbpedia](https://github.com/aws/graph-notebook/tree/main/additional-databases/dbpedia) example

**Expected behavior**
The blazegraph example doesn't talk about virtuoso or dbpedia.

**Comment by michaelnchin** [comment]
Hi @ThomasThelen, thank you for the bug report!

The listed Blazegraph documentation issues in `additional-databases` have been addressed in #198 .

I think we can can consider this issue resolved; please feel free to reopen if you have any further questions or concerns.
