### ISSUE TITLE
Allow users to configure gremlin traversal source name

### ISSUE THREAD

**Issue by cdegroc** [aws/graph-notebook#206]
JanusGraph allows to dynamically create multiple graphs, along with their traversal source, using a `ConfiguredGraphFactory` ([doc](https://docs.janusgraph.org/operations/configured-graph-factory/)).

When using a `ConfiguredGraphFactory`, the gremlin traversal is not named `"g"`, as is commonly the case with other TinkerPop-enabled graph DBs, but `"<graph_name>_traversal"` ([doc](https://docs.janusgraph.org/operations/configured-graph-factory/#graph-and-traversal-bindings)).

Therefore, would it be possible to make the traversal source name configurable instead of [hardcoding it to "g" in client.py](https://github.com/aws/graph-notebook/blob/main/src/graph_notebook/neptune/client.py#L166)?

It would make sense to me to configure the traversal source name from a dedicated section in `graph_notebook_config`, i.e. 
```
%%graph_notebook_config
{
  "host": "localhost",
  "port": 8182,
  "ssl": false,
  "gremlin": {
    "traversal_source": "my_graph_traversal"
  }
}
```

Note that I've tried updating `client.py` locally to use a different traversal name (`<graph_name>_traversal`) and graph-notebook then worked perfectly with JanusGraph.

**Comment by michaelnchin** [comment]
@cdegroc `traversal_source` configuration option has added in the suggested format with [Release 3.0.8](https://github.com/aws/graph-notebook/releases/tag/v3.0.8). 

Again, thank you for the feature suggestion. Please feel free to re-open this issue if you have any further questions or concerns.
