### ISSUE TITLE
Add a button to download query results 

### ISSUE THREAD

**Issue by brianok-aws** [aws/graph-notebook#211]
**Is your feature request related to a problem? Please describe.**
When I run a SPARQL query in the notebook, I am frustrated there’s no option to download the data as a CSV or other file format. 

**Describe the solution you'd like**
I would like to have a "download" button to download the result set in my browser.

**Describe alternatives you've considered**
I can issue HTTP requests or write code to save the results to a file and write the file to my Neptune instance, but that is not friendly to my data scientist team and will likely add a lot of small files to my notebook instance file system.

**Comment by richraid21** [comment]
I ran into this problem yesterday where I was doing some exploration of the graph and needed some quick results, but the result set was large enough that printing it as CSV via Pandas was too taxing on the browser. I ended up needed to rewrite the query in Java and run it to save the results.
