### ISSUE TITLE
Resizing of query result cells

### ISSUE THREAD

**Issue by brianok-aws** [aws/graph-notebook#214]
**Is your feature request related to a problem? Please describe.**
As a user, I get frustrated when the results of my query are too large for the visible pane and I need to use scrollbars to access it.  If the rows are not near each other, I cannot visually compare the results side by side without scrolling.

**Describe the solution you'd like**
I would like the ability to drag and drop the edge of the results pane so I can resize it vertically and horizontally and view all of my results without scrolling (limited to the screen/browser size of course)

**Describe alternatives you've considered**
The sample notebooks provide a code snippet that allow horizontal resizing to 100% of the screen, but not vertical resizing.

**Additional context**

**Comment by michaelnchin** [comment]
A `--no-scroll` option is now available in all query magics, this allows for resizing the vertical limit of the query results table to unrestricted length.
