### ISSUE TITLE
Support selection of media type in %%sparql cell magics

### ISSUE THREAD

**Issue by brianok-aws** [aws/graph-notebook#215]
**Is your feature request related to a problem? Please describe.**
When using the %%sparql cell magic, I cannot change the media type that the results are printed in.  If I was submitting an HTTP query, I would be able to. 

**Describe the solution you'd like**
I would like a parameter to be added to the %%sparql magic to allow me to specify the media type to output the results in.  For example, there is a long list of media types supported in Neptune listed at https://docs.aws.amazon.com/neptune/latest/userguide/sparql-media-type-support.html

**Describe alternatives you've considered**
Writing HTTPS requests in Python to achieve this is not user friendly, non-programmer friendly, and loses the convenience of the %%sparql magic.

**Additional context**

**Comment by michaelnchin** [comment]
A media type parameter (`--media-type`/`-m`) had been added to `%%sparql` with #313. Resolving.
