### ISSUE TITLE
[BUG] Summarize the issue in a few words here

### ISSUE THREAD

**Issue by snowolf** [aws/graph-notebook#224]
**Describe the bug**
In the [notebook](https://github.com/aws/graph-notebook/blob/main/src/graph_notebook/notebooks/04-Machine-Learning/Neptune-ML-01-Introduction-to-Node-Classification-Gremlin.ipynb), when create endpoint, it should be :

```
endpoint_params=f"""
--id {training_job_name}
--model-training-job-id {training_job_name} """
```

Right now, there is more than one - in **model-training-job-id** as below, which should remove one - between the word _model_ and _training_.

```
endpoint_params=f"""
--id {training_job_name}
--model--training-job-id {training_job_name} """
```

**Comment by michaelnchin** [comment]
@snowolf, thank you for the bug report! The listed typo is now fixed with commit https://github.com/aws/graph-notebook/commit/4d73255537094062e35cd01e337f93640dbb5394.
