### ISSUE TITLE
[BUG] Auto complete using the TAB key no longer works

### ISSUE THREAD

**Issue by krlawrence** [aws/graph-notebook#229]
I'm not sure when it stopped working but at least in the 3.0.8 release, pressing the TAB key while entering a query no longer offers a drop-down of auto completion hints.

It is possible to re-enable it by entering the command

```
%config Completer.use_jedi = False
```

**Comment by michaelnchin** [comment]
This is caused by a bug where`ipython<=7.19.0` pulls in `jedi>=0.18.0` which is incompatible: 

https://github.com/ipython/ipython/issues/12740

We can pin the jedi version to 0.17 to patch this.
