### ISSUE TITLE
Support different sparql explain return formats

### ISSUE THREAD

**Issue by austinkline** [aws/graph-notebook#26]
**Describe the solution you'd like**
Support for different sparql explain formats in the `%%sparql explain` variant fo the `%%sparql` command. [Link to public doc](https://docs.aws.amazon.com/neptune/latest/userguide/sparql-explain-examples.html#sparql-explain-output-options)

**Comment by michaelnchin** [comment]
Looks like we added an `--explain-format` option for `%%sparql` in the Neptune Client update (https://github.com/aws/graph-notebook/pull/104):

https://github.com/aws/graph-notebook/blob/997ace373b308a0144a14e2dd45b715678822942/src/graph_notebook/magics/graph_magic.py#L198

Closing, as the issue has been addressed.
