### ISSUE TITLE
[BUG] Summarize the issue in a few words here

### ISSUE THREAD

**Issue by richardtiffin** [aws/graph-notebook#266]
Running the following command:
`%load -s {response} -f csv -p OVERSUBSCRIBE --run`
in the notebook: https://aws-neptune-neptunenotebook.notebook.eu-west-2.sagemaker.aws/notebooks/Neptune/04-Machine-Learning/Neptune-ML-00-Getting-Started-with-Neptune-ML-Gremlin.ipynb
produces the error:
`UsageError: option -f not recognized ( allowed: "yns:r:" )`

**Comment by michaelnchin** [comment]
Hi @richardtiffin, thank you for the bug report! 

I was not able to reproduce this bug with a notebook created via the [NeptuneML quick-start CloudFormation template](https://docs.aws.amazon.com/neptune/latest/userguide/machine-learning-quick-start.html) in our public documentation:
![Issue_266](https://user-images.githubusercontent.com/10456376/154598775-7d4e042b-bcd1-4edb-9912-53658a87dd9e.png)

**Comment by michaelnchin** [comment]
Could you also provide the Python version of your environment, as well as the version of graph-notebook being used? These can be found by running the below commands in your notebook:
![Screen Shot 2022-02-17 at 5 16 25 PM](https://user-images.githubusercontent.com/10456376/154599194-7b32baa0-ee3d-4aa8-a991-66a4083150e7.png)

**Comment by michaelnchin** [comment]
Closing due to 30 days of inactivity. Please do re-open if you have more information about reproducing the issue.
