### ISSUE TITLE
Error installing widgets nbextensions with version 3.3.0

### ISSUE THREAD

**Issue by zfein** [aws/graph-notebook#285]
**Describe the bug**
I'm running into the same issue from https://github.com/aws/graph-notebook/issues/83 with the newest version of the graph-notebook library, 3.3.0, with python 3.7.9.

**To Reproduce**

```
python -m venv env
source env/bin/activate
pip install -r requirements.txt

jupyter nbextension install --py --sys-prefix graph_notebook.widgets
```

requirements.txt

```
notebook==6.4.10
tornado==6.1
graph-notebook==3.3.0
```

`jupyter nbextension install --py --sys-prefix graph_notebook.widgets` returns the error:

```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/{user}/test_graph_notebook/env/lib/python3.7/site-packages/graph_notebook/widgets/nbextension/static'
```

running `which jupyter` returns /Users/{user}/test_graph_notebook/env/bin/jupyter

**Comment by michaelnchin** [comment]
Hi @zfein,

As a change introduced in graph-notebook version 3.3.0, the `jupyter nbextension install ...` step is no longer required to install the widgets extension on Jupyter classic notebooks. 

Please refer to the [updated installation process](https://github.com/aws/graph-notebook#installation) in the README for additional information, and let us know if this resolves your issue.
