### ISSUE TITLE
[BUG] Fresh JupyterLab install fails to load `graph_notebook.magics` (needs PR #277)

### ISSUE THREAD

**Issue by fedonev** [aws/graph-notebook#289]
**Describe the bug**
 A first-time  install  @v3.3.0 and JupyterLab fails to load the graph-notebook magics unless you manually add the `graph_notebook.magics` extension to `~/.ipython/profile_default/ipython_config.json`.   This is fixed with the start-up script in PR #277 .

```bash
UsageError: Cell magic `%%graph_notebook_config` not found.
```

**To Reproduce**
1. Follow the JupyterLabs install instructions in the README.

**Expected behavior**
Magic!

**Desktop (please complete the following information):**
 - OS: macOS Monterrey
 - Browser chrome
 - Version 100

**Additional context**
Fixed by manually applying the `configure_ipython_profile()` method from `start_jupyterlab.py` pending in PR #277

**Comment by michaelnchin** [comment]
Hi @fedonev,

Thanks for the bug report! We will prioritize inclusion of PR #277 in the next release. I'll add some temporary workarounds to the README in case others run into similar issues on v3.0.3.

**Comment by michaelnchin** [comment]
PR #277 is merged, closing this issue.
