### ISSUE TITLE
[BUG] EFL-SPARQL notebook CONSTRUCT does not filter to just EFL

### ISSUE THREAD

**Issue by mikebrules** [aws/graph-notebook#293]
**Describe the bug**
In the EFL-SPARQL notebook, when you run "Delete or view the entire data set" step (Box 30) you would expect the CONSTRUCT to filter to just the soco example. But in fact it generates triples for every aspect of the graph, including (what I presume is) the system constructs. 

**To Reproduce**
1. Run the notebook (open http://localhost:8888/notebooks/02-Visualization/EPL-SPARQL.ipynb)
2. Follow each step of the notebook until step 30
3. Execute Step 30 (the Construct Statement)

**Expected behavior**
Given the filter, I would expect the result set of the graph statement to return the EFL "World" only but that filter does not happen. As a result, all subsequent queries also return a much broader set of data (including the system itself).

**Screenshots**

<img width="1009" alt="Screenshot 2022-04-25 at 08 34 46" src="https://user-images.githubusercontent.com/562460/165041849-7a2bb336-a7da-480b-8942-5ec4982a5e4a.png">

**Desktop (please complete the following information):**
 - OS - Mac OS Big Sur
 - Browser [e.g. chrome, safari] - Chrome 100.0.4896.127

**Additional context**
All subsequent queries appear to return the entirety of the grah, not just the EFL example

**Comment by michaelnchin** [comment]
Hi @mikebrules, thank you for the bug report!

I'm having some trouble reproducing the behavior shown, so may need additional context here.

Running `graph-notebook==3.3.0` on Neptune releases 1.1.0.0 and 1.1.1.0, I saw the following when running the same CONSTRUCT query in the EPL notebook. There were quite a few more results returned, but all belonged to the inserted EPL dataset, though the Neptune database also has the air-routes RDF dataset loaded.

![Screen Shot 2022-04-25 at 4 33 50 PM](https://user-images.githubusercontent.com/10456376/165191186-34c941f4-4202-46db-a1a2-606412ceeb82.png)

For debugging purposes, could you confirm what version of graph-notebook is being used, as well as your graph database engine and version? Also, could you provide a text file or similar with your full query results in JSON format?

**Comment by krlawrence** [comment]
I believe the test was being run on a local database, not Neptune, looking at the information in the original report. The `FILTER` is supposed to only pick up the EPL triples and in my testing worked accordingly on Neptune. @mikebrules which RDF store were you using when you observed this behavior?

**Comment by michaelnchin** [comment]
Closing due to >3 months of inactivity. Please re-open if you are able to provide additional information that can help reproduce the issue.
