### ISSUE TITLE
Question: How to create Python function for Gremlin?

### ISSUE THREAD

**Issue by kangks** [aws/graph-notebook#295]
I would like to encapsulate the nodes creation with a Python function as follow, but encountered error parsing. How do I go about creating a Python function?

```
%%gremlin 
def addPerson(firstName, lastName, displayName):
    g.addV('person').property('firstName', firstName).property('lastName', lastName).property('displayName', displayName).next()
```
However when I execute it I encountered error

```
{
  "code": "MalformedQueryException",
  "requestId": "17a4b991-d811-48f0-9464-767cf0f4a76d",
  "detailedMessage": "Failed to interpret Gremlin query: Query parsing failed at line 1, character position at 2, error message : token recognition error at: 'f '"
}
```

**Comment by michaelnchin** [comment]
Hi @kangks, the `%%gremlin` magic can only accept a properly formatted Gremlin query as the cell body input. It would not be able to define a function in the manner that you described.

Here's an example of a workaround we can use to define an equivalent function: 

```
def addPerson(firstName, lastName, displayName):
    global firstname_temp, lastname_temp, displayname_temp
    firstname_temp = firstName
    lastname_temp = lastName
    displayname_temp = displayName
    get_ipython().run_cell_magic(
        magic_name="gremlin", 
        line="", 
        cell="g.addV('person').property('firstName', '${firstname_temp}').property('lastName', '${lastname_temp}').property('displayName', '${displayname_temp}').next()"
    ) 
```

Using iPython's built-in `run_cell_magic` method, we can translate the entire `%%gremlin` cell magic into a single line, and call it from within the function definition. Additionally, the `${VAR}` syntax is needed to reference variables from within the cell magic body. Cell magic variables are read from the global notebook namespace, so we also need to define and use new global variables from the function parameter values.

Let us know if this works for you, and if you have any further questions

**Comment by kangks** [comment]
> 

That works, thanks! Closing this.
