### ISSUE TITLE
Error displaying widget

### ISSUE THREAD

**Issue by anezkakot** [aws/graph-notebook#298]
**Describe the bug**
When I run tutorial notebooks and the result should be visualized, it gives me an error: "Error displaying widget". For queries without a path, it gives tabs "Console" and "Query Metadata" without any problems.

**To Reproduce**
I run it on JupyterLab 3.2.8 (I tried it with 3.4.2 but the result was the same). Python version 3.9.7

**Expected behavior**
I would love to see the results from the queries. Any idea of what could help will be appreciated.

**Screenshot**
<img width="1054" alt="Screenshot 2022-05-23 at 16 59 26" src="https://user-images.githubusercontent.com/90032032/169849235-976754b3-4b86-4150-bf9c-71b69d6807a9.png">

**Comment by alexandrututunaru** [comment]
I have the same problem. This is what I tried:

mamba create -n test12 python=3.8 (which installed 3.8.13)
conda activate test12
pip install rdflib==5.0.0
pip install markupsafe==2.0.1
pip install graph-notebook
pip install jupyterlab==3.2.8

The installation of jupyerlab returned the error:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
graph-notebook 3.3.0 requires nbconvert==5.6.1, but you have nbconvert 6.5.0 which is incompatible.

I then ran pip install nbconvert==5.6.1
and got
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jupyter-server 1.17.0 requires nbconvert>=6.4.4, but you have nbconvert 5.6.1 which is incompatible.

I then ran
pip install jupyter_server==1.13.4
and I got no more conflicts. Afterwards, I loaded the magics, configured the Neptune details and seeded/loaded the air routes data

If I execute
%%gremlin
g.V().groupCount().by(label).unfold()
I get results

If I execute
my_node_labels = '{"airport":"city"}'
my_edge_labels = '{"route":"dist"}'
%%gremlin -p v,oute,inv -d $my_node_labels -l 20 -g country -de $my_edge_labels
g.V().has('code','LHR').outE().inV().path().by(valueMap(true)).limit(5)
I get 'Error displaying widget'

I tried the same procedure for python versions 3.6.13, 3.7.13, 3.9.7 (for this I also had to install matplotlib) and the results were the same. I attached a file with the results of pip freeze

[req.txt](https://github.com/aws/graph-notebook/files/8762409/req.txt)

**Comment by michaelnchin** [comment]
Hi @anezkakot, thank you for the bug report, and apologies for the late response.

I spent some time trying to reproduce this bug on JupyterLab 3.2.8 following the installation info provided (also that from @alexandrututunaru), but have not yet been successful.

To help better understand the root cause, could either of you also provide:

1. The output of `!jupyter labextension list`
2. The JavaScript errors displayed in console of your browser's web developer tools, after running a query where the widget failed to display

**Comment by michaelnchin** [comment]
For reference, these configurations on Python 3.6.13 and 3.9.7 display the graph widget correctly on my local setup:

[freeze_3.6.13_v3.3.0_noconflicts.txt](https://github.com/aws/graph-notebook/files/8875127/freeze_3.6.13_v3.3.0_noconflicts.txt)
[freeze_3.9.7_v3.3.0_noconflicts.txt](https://github.com/aws/graph-notebook/files/8875128/freeze_3.9.7_v3.3.0_noconflicts.txt)

**Comment by michaelnchin** [comment]
Closing due to >3 months of inactivity. Please re-open this issue if you are able to provide additional information that can help reproduce the error.

**Comment by miguelsmuller** [comment]
I'm having this same problem when I try to use jupyterlab > 4 .

It works
```
jupyter==1.0.0
jupyter-client==7.1.2
jupyter-console==6.4.3
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.9.2
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
jupyter-server==1.13.1
jupyterlab==3.2.8
jupyterlab-server==2.10.3
jupyterlab-widgets==1.1.0
pandas==1.5.3
graph-notebook==3.8.2
ipykernel
```

This generates error `Error displaying widget`
```
jupyter==1.0.0
jupyter-client==8.3.0
jupyter-console==6.4.3
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1

jupyter-core==5.3.1
jupyter-server==2.7.0
jupyterlab==4.0.2
jupyterlab-server==2.23.0

jupyterlab-widgets==1.1.0
pandas==1.5.3
graph-notebook==3.8.2
ipykernel

```
