### ISSUE TITLE
[BUG] SPARQL Construct raw output is not RDF (wrong request headers?)

### ISSUE THREAD

**Issue by giacomociti** [aws/graph-notebook#303]
**Describe the bug**

The raw output for a construct query is not in any valid RDF format (N-Quads should be the default according to [docs](https://docs.aws.amazon.com/neptune/latest/userguide/sparql-media-type-support.html)).

**To Reproduce**

Enter the following query:

``` sparql
%%sparql
PREFIX : <http://test/>

CONSTRUCT { :x :foo :bar  } WHERE { }

```

and look at the Raw result tab.

**Expected behavior**
something like:

``` turtle
<http://test/x> <http://test/foo> <http://test/bar>
```

**Actual behavior**

```
http://test/x http://test/foo http://test/bar
```

Using the notebook with other endpoints (e.g. [comunica](https://comunica.dev/)) I get 
[400] Bad request, invalid media type

I suspect [here](https://github.com/aws/graph-notebook/blob/65a89d71dab66345f27a105e2ea4d68787bdf5f1/src/graph_notebook/magics/graph_magic.py#L339) we are using the `application/sparql-results+json` Accept header also for CONSTRUCT and DESCRIBE queries.

**Comment by krlawrence** [comment]
Thanks for the issue @giacomociti - We are looking into it
