### ISSUE TITLE
Workbench visualization multiple edges between two vertices have labels overlap 

### ISSUE THREAD

**Issue by bechbd** [aws/graph-notebook#31]
When you have two vertices with different edge labels between them they are being shown as two overlapping edges. This causes an issue where you cannot read either edge label. See attached images.

DETAILS:
I. We need to show different edge labels between two vertices as different edges, or we need to concatenate them so that they don't overlap making them unreadable
![Screen Shot 2020-08-18 at 3 18 56 PM](https://user-images.githubusercontent.com/6898505/99727725-e14dca80-2a64-11eb-834e-1349002ae6db.png)
![Screen Shot 2020-08-18 at 3 19 00 PM](https://user-images.githubusercontent.com/6898505/99727731-e3178e00-2a64-11eb-92ee-18ea674d1b49.png)

**Comment by michaelnchin** [comment]
Users can separate the overlapping edges by re-running `%%graph_notebook_vis_options` with the value of `"edges"`->`"smooth"`->`"type"` changed from the default `straightCross` to `dynamic`. 

More details at Issue https://github.com/aws/graph-notebook/issues/157.

**Comment by michaelnchin** [comment]
We have updated the sample notebooks with an example of the above, in #366. Resolving.
