### ISSUE TITLE
Allow specifying the property shown on the node

### ISSUE THREAD

**Issue by bechbd** [aws/graph-notebook#34]
**Is your feature request related to a problem? Please describe.**
I would like to be able to provide the property name that I would like displayed on the node.

**Describe the solution you'd like**
Currently, the name of the property displayed on the node.  I would like to be able to specify the property that will be displayed

**Comment by paulfryer** [comment]
I would like to be able to specify the node property to display on the graph visualization. Currently the class of the node is shown, but what I actually want to see the "Name" of the node. Often nodes are about things that have names, like a "Company Name" or a "City Name", etc. Those would be the target label's I'd like to show. Now the color of the node could continue to be driven by the class of the node so all Companies could be yellow, Cities could be blue, etc.

**Comment by michaelnchin** [comment]
This is implemented as of release 2.1.4.
