### ISSUE TITLE
Allow specifying the length of the label before truncation

### ISSUE THREAD

**Issue by bechbd** [aws/graph-notebook#35]
**Is your feature request related to a problem? Please describe.**
Currently, the length of the label is truncated at 10.  I would like to be able to specify the label length

**Comment by abdkhaa** [comment]
+1

I'm also experiencing undesirable views in my Neptune graphs due to this issue. Is there any timeline on adding support for this? Just so I have an idea

**Comment by krlawrence** [comment]
Closing as this feature is now implemented.
