### ISSUE TITLE
How to specify a Blazegraph namespace

### ISSUE THREAD

**Issue by fils** [aws/graph-notebook#39]
The current Blazegraph config works for me in my setup.

```
%%graph_notebook_config
{
  "host": "1.2.3.4",
  "port": 80,
  "auth_mode": "DEFAULT",
  "iam_credentials_provider_type": "ROLE",
  "load_from_s3_arn": "",
  "ssl": false,
  "aws_region": "us-east-1"
}
```

but this seems to only connect to the default "kb" namespace, distinct from the named graph concept.  

Is there a value in the config I can use to specify a namespace I create in Blazegraph.

I use things like 

```
http://1.2.3.4/blazegraph/namespace/dev/sparql>
```

for example for a namespace "dev".  

Something like:

```
"namespace": "dev",
```
or even allow a specific SPARQL endpoint URl like
```
"endpoint": "blazegraph/namespace/dev/sparql"
```

**Comment by triggan** [comment]
For that particular use case, you should use `1.2.3.4/blazegraph/namespace/dev` as your `host` value in the graph_notebook_config (stripping the `http://` prefix and the `/sparql` suffix).

**Comment by fils** [comment]
So for

```
{
  "host": "1.2.3.4/blazegraph/namespace/combined",
  "port": 80,
  "auth_mode": "DEFAULT",
  "iam_credentials_provider_type": "ROLE",
  "load_from_s3_arn": "",
  "ssl": false,
  "aws_region": "us-east-1"
}
```

I get the error

```
{'error': HTTPError('404 Client Error: Not Found for url: http://1.2.3.4/blazegraph/namespace/combined:80/sparql')}
```

It seems it is putting the port on the end of the host string + path, not parsing out the host and putting the port there, before the path.

**Comment by afk314** [comment]
Same issue here running with Jena.  I really look forward to using this magic though!

**Comment by austinkline** [comment]
Plan for this is to alter our configuration to start separating out certain bits that are language specific. For now, that would be sparql having its own sub-piece which is optional. Once this work is done, the configuration would look something like below:

```
{
  "host": "change-me",
  "port": 8182,
  "auth_mode": "DEFAULT",
  "iam_credentials_provider_type": "ROLE",
  "load_from_s3_arn": "",
  "ssl": true,
  "aws_region": "us-east-1",
  "sparql": {
    "path": "blazegraph/namespace/combined"
  }
}
```

**Comment by chihpoc** [comment]
> Same issue here running with Jena. I really look forward to using this magic though!

did you figure out a way to use graph-notebook with jena?
