### ISSUE TITLE
[BUG] Returning tree() throws an error

### ISSUE THREAD

**Issue by bechbd** [aws/graph-notebook#396]
**Describe the bug**
An error is returned when you run a `tree()` query with the Gremlin magic.

**To Reproduce**
Run a Gremlin query that returns a `tree()` like this:

```
%%gremlin

g.V().limit(1).tree()
```

This error is displayed
```
{'error': KeyError(<DataType.tree: 43>)}
```

**Expected behavior**
To show the result

**Comment by michaelnchin** [comment]
Resolved with release 3.7.0.
