### ISSUE TITLE
[BUG] Proxy configuration is not respected by Gremlin driver

### ISSUE THREAD

**Issue by vcaraulean** [aws/graph-notebook#399]
While configuring Gremlin driver using configuration magic it seems like the settings for proxy aren't used by the driver.

**To Reproduce**

Configuration:
```
%%graph_notebook_config
{
  "host": "my-host",
  "port": 3000,
  "ssl": true,
  "proxy_host": "http://my-proxy.com",
  "proxy_port": 4000
}
```

Executing following gremlin query:
```
%%gremlin

g.V().limit(10)
```

Displayed error:
```json
{'error': ClientConnectorError(ConnectionKey(host='my-host', port=3000, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), gaierror(11001, 'getaddrinfo failed'))}
```

**Expected behavior**

I would expect WebSockets connection to use the specified proxy.

Part of the error indicates `proxy=None`, so I assume it's not the case.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: latest

I'm filling it as a bug, but it might be that passing of the proxy to WebSockets driver was simply not implemented. Happy to requalify as a "feature" then.

PS: I tried to use the Gremlin's driver in a new Jupiter notebook and initially hit same error/issue. After fiddling around, I found correct setting to make the driver connect to our endpoints and passing through the proxy. Relevant code:
```python
connection = DriverRemoteConnection(endpoint,'g', transport_factory=lambda:AiohttpTransport(
        call_from_event_loop=True, 
        proxy = os.getenv('HTTP_PROXY')))
```

**Comment by michaelnchin** [comment]
Thank for the report @vcaraulean , we are looking into a fix.

**Comment by triggan** [comment]
@vcaraulean  For your proxy host, you do not need to prefix that with `http://`.  That should just be the hostname of your proxy (load balancer endpoint, in most cases).
