### ISSUE TITLE
[BUG] No documentation on how to connect local notebook to remote Neptune SSL

### ISSUE THREAD

**Issue by faizaamer** [aws/graph-notebook#40]
**SSL Connection to remote Neptune not working**
I am unable to figure out how can I specify the correct certificate SFSRootCAG2.pem when running queries against SSL-enabled Neptune.

**To Reproduce**
1. I set up SSH tunnel via bastion to the Neptune cluster '_ssh -i keypairfilename.pem ec2-user@yourec2instanceendpoint -N -L 8182:yourneptuneendpoint:8182_'
2. I start graph-notebook as '_jupyter notebook notebook/destination_neptune_'. This gives me the output _Jupyter Notebook 6.1.5 is running at: http://localhost:8888/?token=13b2761a59217f9246aed1dab73e70c3ae42973c4339f328_
3. I open my notebook and run the following magic commands 
_'%%graph_notebook_config
{
  "host": "localhost",
  "port": 8182,
  "auth_mode": "DEFAULT",
  "iam_credentials_provider_type": "ROLE",
  "load_from_s3_arn": "",
  "aws_region": <myregion>,
  **"ssl": true**
}'_
4. I run the command 
_%%sparql        
SELECT * WHERE {?s ?p ?o} LIMIT 1_

5. It gives me the error
**{'error': SSLError(MaxRetryError('HTTPSConnectionPool(host=\'localhost\', port=8182): Max retries exceeded with url: /sparql (Caused by SSLError(SSLCertVerificationError("hostname \'localhost\' doesn\'t match either of \'*.............**

**Expected behavior**
I expect to be able to connect to a remote neptune that has ssl enabled.

**Screenshots**
None

**Desktop (please complete the following information):**
 - macOS 10.15.7 Catalina
 - Browser Chrome
 - Version 86.0.4240.198 (Official Build) (x86_64)

**Additional context**
Add any other context about the problem here.None

**Comment by austinkline** [comment]
Looks like we have a missing piece in our walkthrough for connecting to Neptune:

https://github.com/aws/graph-notebook/tree/main/additional-databases/neptune

Could you give setting your hostname from localhost to your Neptune endpoint:

```
%graph_notebook_host <your endpoint here>
```

And give it a try?

**Comment by faizaamer** [comment]
I  updated /etc/hosts on my Mac and added an alias for localhost as

> _27.0.0.1       localhost    yourneptuneendpoint_

Flushed DNS cache.
Set the hostname in Jupyter notebook graph_notebook_config command to **yourneptuneendpoint**.
Ran sparql query and it successfully completed.

**Comment by austinkline** [comment]
Glad it worked! I have filed an issue for us to expand our documentation to cover the steps you had to take. Closing this but feel free to open or submit a new issue if you need further assistance
