### ISSUE TITLE
[BUG] Cell magic not found

### ISSUE THREAD

**Issue by whitehorsesoft** [aws/graph-notebook#413]
**Cell magic not found**
Cell magic such as `%%graph_notebook_config` and `%%status` not found.

**To Reproduce**
1. Run docker image [jupyter/minimal-notebook](https://hub.docker.com/r/jupyter/minimal-notebook).
2. Open in browser
3. Verify normal notebook functionality works without graph-notebook.
4. Install graph-notebook using the commands found [here](https://github.com/aws/graph-notebook#installation):
```bash
# pin specific versions of required dependencies
pip install rdflib==5.0.0

# install the package
pip install graph-notebook
```
5. Attempt to change configuration according to directions [here](https://github.com/aws/graph-notebook#gremlin-server):
```jupyter
%%graph_notebook_config
{
  "host": "localhost",
  "port": 8182,
  "ssl": false,
  "gremlin": {
    "traversal_source": "g",
    "username": "",
    "password": "",
    "message_serializer": "graphsonv3"
  }
}
```
6. Error occurs: "UsageError: Cell magic `%%graph_notebook_config` not found."
7. Verify error happens even after restarting kernel and restarting docker container.
**Expected behavior**
The cell magic should work as expected.

**Desktop (please complete the following information):**
 - OS: Win10/WSL/Ubuntu
 - Browser Chrome
 - Version latest

**Comment by michaelnchin** [comment]
Hi @whitehorsesoft, thank you for submitting a bug report.

Can you confirm if you have also run the remaining installation commands for Jupyter Notebook [here](https://github.com/aws/graph-notebook#jupyter-classic-notebook)?

Also, please try running the commands documented [here](https://github.com/aws/graph-notebook#loading-magic-extensions-in-jupyterlab) to manually configure the magics extension:

```
python -m graph_notebook.ipython_profile.configure_ipython_profile
```

**Comment by whitehorsesoft** [comment]
@michaelnchin since I'm using a docker instance, there is no need to go through the commands to install jupyter notebook or jupyter lab. So for example the command `pip install "jupyterlab>=3"` is not needed.

I forgot to put in the original bug report, but I did run
```bash
python -m graph_notebook.ipython_profile.configure_ipython_profile
```
...but there is no change, I am still getting the same errors as in the original bug report.

**Comment by michaelnchin** [comment]
Thank you for the additional details @whitehorsesoft.

I was able to reproduce on my side. During installation, loading of some extensions appears to fail silently in relation to [this open issue](https://github.com/aws/graph-notebook/pull/416).

As a workaround until we can get the fix into a release, please run the following modified installation sequence from a Terminal window in the JupyterLab instance. I have verified that this works on a local instance of jupyter/minimal-notebook.

```
# pre-install patched dependencies
pip install rdflib==5.0.0
pip install numpy==1.23.5

# install graph-notebook and sample notebooks onto instance
pip install graph-notebook
python -m graph_notebook.notebooks.install --destination ~/notebook/destination/python -m graph_notebook.notebooks.install --destination ~/notebook/destination/dir

# configure auto-loading of graph_notebook.magics extension
python -m graph_notebook.ipython_profile.configure_ipython_profile

# restart browser window to load the graph_notebook.widgets extensions
```

**Comment by michaelnchin** [comment]
Thanks for confirming. Closing the issue, please do reopen if you have any further questions.
