### ISSUE TITLE
[BUG] Cannot issue Gremlin queries

### ISSUE THREAD

**Issue by whitehorsesoft** [aws/graph-notebook#418]
**Describe the bug**
Using the steps described in the [setup](https://github.com/aws/graph-notebook/tree/main/additional-databases/gremlin-server) results in an error:
```
{
'error': GremlinServerError
  (
    '597: No signature of method: org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph.addV() is applicable for argument types: (String) values: [person]
    Possible solutions: any(), any(groovy.lang.Closure), wait(), open(), tx(), find()'
  )
}
```

**To Reproduce**
1. Download the Gremlin Server from https://tinkerpop.apache.org/ and unzip it. The remaining steps in this section assume you have made your working directory the place where you performed the unzip.
2. In conf/tinkergraph-empty.properties, change the ID manager from `LONG` to `ANY` to
   enable IDs that include text strings.
   ```
   gremlin.tinkergraph.vertexIdManager=ANY
   ```
3. Optionally add another line doing the same for edge IDs.
   ```
   gremlin.tinkergraph.edgeIdManager=ANY

   ```
4. To enable HTTP as well as Web Socket connections to the Gremlin Server, edit the file /conf/gremlin-server.yaml and change
   ```
   channelizer: org.apache.tinkerpop.gremlin.server.channel.WebSocketChannelizer
   ```
   to
   ```
    channelizer: org.apache.tinkerpop.gremlin.server.channel.WsAndHttpChannelizer
   ```
   This will allow you to access the Gremlin Server from Jupyter using commands like `curl` as well as using the `%%gremlin` cell magic. This step is optional if you do not need HTTP connectivity to the server.
5. Start the Gremlin server `bin/gremlin-server.sh start`

Connecting to a local Gremlin Server from Jupyter:
1. In the Jupyter Notebook disable SSL using `%%graph_notebook_config` and change the host to `localhost`. Keep the other defaults even though they are not used for configuring the Gremlin Server.
```
%%graph_notebook_config
{
  "host": "localhost",
  "port": 8182,
  "ssl": false,
  "gremlin": {
    "traversal_source": "g",
    "username": "",
    "password": "",
    "message_serializer": "graphsonv3"
  }
}
```
If the Gremlin Server you wish to connect to is remote,  replacing `localhost` with the IP address or DNS of the remote server should work. This assumes you have access to that server from your local machine.
1. Validate connection.
```
%status
```

1. Issue query (from [here](https://github.com/aws/graph-notebook/blob/main/src/graph_notebook/notebooks/01-Getting-Started/01-About-the-Neptune-Notebook.ipynb))
```
%%gremlin

g.addV('person').property('name', 'dan')
 .addV('person').property('name', 'mike')
 .addV('person').property('name', 'saikiran')
```

**Expected behavior**
The vertices should be added with no error messages.

**Desktop (please complete the following information):**
 - Gremlin Server version: 3.6.1
 - JupyterLab version: 3.5.1
 - OS: Windows 10 / Debian Bullseye
 - Browser: Firefox, Chrome

**Comment by krlawrence** [comment]
That looks like the `g` exported by the Gremlin Server config files is not a traversal, but rather the TinkerGraph itself. Can you please check that the `gremlin-server.yaml` file in the `/conf` folder (or a different YAML file if you have a custom one) is invoking an appropriate Groovy script in the `/scripts` folder. That is where the `g` gets bound (server side). By default it usually invokes `empty-sample.groovy` which includes the line:
```
globals << [g : traversal().withEmbedded(graph).withStrategies(ReferenceElementStrategy)]
```

**Comment by whitehorsesoft** [comment]
> Can you please check that...is invoking an appropriate Groovy script...

I can confirm.

It is using conf/gremlin-server.yaml (as per the directions).

The scriptEngines section of that .yaml file does contain a files section, which points to scripts/empty-sample.groovy.

empty-sample.groovy does indeed have the line you mentioned above (starting with `globals << ...`.

**Comment by whitehorsesoft** [comment]
fwiw when I start the server, there is a warning message:

> WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:[leaving out full path here]/apache-tinkerpop-gremlin-server-3.6.1/lib/groovy-2.5.14-indy.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by whitehorsesoft** [comment]
Okay, thanks in part to starting to read [your book](https://www.kelvinlawrence.net/book/PracticalGremlin.html), I think I found the issue, I had inadvertently changed the configuration traversal source in the Jupyter notebook. Things seem to be working now, ty for the assistance!

**Comment by krlawrence** [comment]
I'm happy to hear it's working. Best wishes. Kelvin
