### ISSUE TITLE
Truncate query request time in metadata

### ISSUE THREAD

**Issue by jklap** [aws/graph-notebook#422]
Currently the query metadata reports a query request time in ms with a large number of decimal places such as:
```
Request execution time (ms) | 189.0205078125
```

Given the resolution of statement execution and network delays, etc, not sure that number of decimals points does anything but make the results harder to read :)

Would suggest we truncate it down to a reasonable number or round it to the closest ms?

**Comment by michaelnchin** [comment]
Thank you for the suggestion @jklap ! This has been implemented, metrics are now rounded to the nearest hundredth of a ms.
