### ISSUE TITLE
[BUG] TypeError: '<' not supported between instances of 'str' and 'int' across multiple queries for multiple notebooks

### ISSUE THREAD

**Issue by characode** [aws/graph-notebook#428]
**Describe the bug**
Any query that is run, error TypeError: '<' not supported between instances of 'str' and 'int'

**To Reproduce**
1. Notebook > run query 
`
%%gremlin
g.V().count()
`
2. See error
`
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/graph_notebook/magics/graph_magic.py in gremlin(self, line, cell, local_ns)
    969                          scrollCollapse=gremlin_scrollCollapse,
    970                          lengthMenu=[final_pagination_options, final_pagination_menu],
--> 971                          pageLength=visible_results
    972                          )
    973                 else:  # Explain/Profile

~/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/itables/javascript.py in show(df, caption, **kwargs)
    386 def show(df=None, caption=None, **kwargs):
    387     """Show a dataframe"""
--> 388     html = to_html_datatable(df, caption=caption, connected=_CONNECTED, **kwargs)
    389     display(HTML(html))

~/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/itables/javascript.py in to_html_datatable(df, caption, tableId, connected, **kwargs)
    229     # Only display the table if the rows fit on one 'page'
    230     if "dom" not in kwargs and len(df) <= 10:  # the default page has 10 rows
--> 231         if "lengthMenu" not in kwargs or len(df) <= min(kwargs["lengthMenu"]):
    232             kwargs["dom"] = "t"
    233 

TypeError: '<' not supported between instances of 'str' and 'int'
`

**Expected behavior**
Query should return results

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MAC 13.0.1
 - Browser chrome
 - Version 109.0.5414.87
![Screenshot 2023-01-16 at 9 33 40 AM](https://user-images.githubusercontent.com/24689068/212715293-982d9afc-485d-43e1-a5cf-642b75368292.png)

**Additional context**

**Comment by shivakumarss** [comment]
+ 1

**Comment by AbhishekOnedigital** [comment]
+1

**Comment by michaelnchin** [comment]
Thank you for the bug report! 

I am able to reproduce this bug locally on v3.7.0. The error shown appears related to a change present in recent versions of our `itables` package (`>=1.4.3`): 

https://github.com/mwouts/itables/commit/e960b46ed9608881b18ad7d3df40a34259a87c3f#diff-4dfccbfcd6268643526f2adf41205a37768913776c49a7e724cee5bd668e8c52R229

I have verified that manually downgrading to `itables==1.4.2` will resolve the error. Will add this version as the ceiling in our setup requirements to mitigate: https://github.com/aws/graph-notebook/blob/main/setup.py#L90

**Comment by michaelnchin** [comment]
Fix is merged, thank you again for the report!

Please note the new setup requirement to install `itables==1.4.2` as a temporary mitigation until our next release: https://github.com/aws/graph-notebook#installation

**Comment by characode** [comment]
Thank you
