### ISSUE TITLE
Add ability to have %seed load from a specific file

### ISSUE THREAD

**Issue by krlawrence** [aws/graph-notebook#44]
Currently the `%seed` line magic loads data by looking for files in a specific location. Today a user could place one or more files into that location and load them using `%seed`.  This requires using the correct file naming scheme and also finding the correct directory to put the files in. A nicer user experience would be to add a parameter allowing them to  provide the name of a file to the `%seed` command. The assumption is that this would be a file on their local disk or the disk of a remote Jupyter server.  I am not proposing the file be on an HTTP server or in an S3 bucket. As part of this we would need to briefly also document the syntax expected for Gremlin or SPARQL data in files loaded by `%seed`.

Something simple like `%seed --file filename` would be a good start. It may also make sense to add this to the widget at some time.

**Comment by michaelnchin** [comment]
Closing as completed.
