### ISSUE TITLE
[BUG] Broken Dockerfile build

### ISSUE THREAD

**Issue by expe-elenigen** [aws/graph-notebook#446]
**Describe the bug**
When trying to build image:
```sh
docker build https://github.com/aws/graph-notebook.git#main:docker
```
> unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /private/var/folders/l2/ndskbl1s7nb6d8392b6gx_j00000gp/T/docker-build-git501517757/docker/Dockerfile: no such file or directory

If I try this instead:
```sh
docker build - < Dockerfile
```
It will start, but it would end up with a different error:

**To Reproduce**
1. Go to the terminal
2. Execute:
    ```sh
    docker build https://github.com/aws/graph-notebook.git#main:docker
    ```

**Expected behavior**
Build the image 

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**
None

**Comment by michaelnchin** [comment]
Hi @expe-elenigen, thank you for submitting a bug report! 

A few observations from testing on MacOS:

For the error with the `docker build` from GitHub URL, you may want to ensure that your local Docker daemon is running first. I was initially able to reproduce with the same command:
```
3c22fb5e1f47:~ chnmch$ docker build https://github.com/aws/graph-notebook.git#main:docker
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /private/var/folders/gd/ls3c1gv97jg44m_t1h4r84qm0000gr/T/docker-build-git2802388090/docker/Dockerfile: no such file or directory
```

Starting Docker Desktop allowed me to bypass this.

However, the command did then fail with a different error:
```
3c22fb5e1f47:~ chnmch$ docker build https://github.com/aws/graph-notebook.git#main:docker
[+] Building 0.0s (1/1) FINISHED                                                                                                                    
 => ERROR [internal] load git source https://github.com/aws/graph-notebook.git#main:docker                                                     0.0s
------
 > [internal] load git source https://github.com/aws/graph-notebook.git#main:docker:
------
failed to solve with frontend dockerfile.v0: failed to read dockerfile: failed to load cache key: subdir not supported yet
```

This is expected behavior, as `docker build` does not yet support building from a subdirectory with git context: https://github.com/docker/build-push-action/issues/673#issuecomment-1234426497

**Comment by michaelnchin** [comment]
Instead of:
```
docker build - < Dockerfile
```

Could you try running:
```
docker build .
```

This will ensure that Docker has access to all of the files in the graph-notebook directory, as required for the build process.

**Comment by michaelnchin** [comment]
Closing due to >30 days of inactivity. Please re-open if there are further updates.

**Comment by expe-elenigen** [comment]
I haven't tried other the other options, but after I did a git pull from master, I was able to build the image with:
```sh
docker build .
```
