### ISSUE TITLE
[BUG] Graph tab not available in JupyterLab Notebook

### ISSUE THREAD

**Issue by rajatb** [aws/graph-notebook#469]
**Community Note**
* Please use a 👍 reaction to provide a +1/vote. This helps the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Describe the bug**
We have JupyterLab version `jupyterlab==3.0.18`, I installed `graph-notebook==3.7.3` extension. When I run a query I do not see the tabs and don't see the option to see the results as a graph. The result I get is in json and console format with metadata. 
Query I tried: 
`%%opencypher -d name
Match pth=(p:Person)-[r:ACTED_IN]->(m:Movie)
return pth Limit 3`

I am using a Python3 notebook. 
 - opencypher': {'version': 'Neptune-9.0.20190305-1.0'}
 - Browser: Google Chrome
 - Graph Notebook Version: 3.7.3
 - Graph Database & Version: , Amazon Neptune 

**To Reproduce**
Look at description above

**Expected behavior**
I would like to see the graph tab so I can see the graph representation of my data.

**Comment by michaelnchin** [comment]
Hi @rajatb , thank you for submitting a bug report!

I attempted to reproduce this issue on my local setup (Python 3.9.7, Google Chrome, Mac OS Monterey) with the same `jupyterlab` and `graph-notebook` versions, but have not been successful.

For us to better assess the root cause, could you provide few more contextual data points about your setup:

- The Python version in your environment
- The output of running `!jupyter labextension list` in a notebook cell (specifically, does `graph_notebook_widgets` show up with `enabled OK` status?)
- Any errors displayed in your browser's Web Developer Tools console, after running an OC query where the graph tab does not display

**Comment by rajatb** [comment]
- The Python version in your environment
  3.8.10

- The output of running !jupyter labextension list in a notebook cell (specifically, does graph_notebook_widgets show up with enabled OK status?)
I get this error when I run this in a cell: 
`/bin/sh: 1: jupyter: not found`

- Any errors displayed in your browser's Web Developer Tools console, after running an OC query where the graph tab does not display
 I don't see any errors in the console.

**Comment by michaelnchin** [comment]
Thank you for the additional information, @rajatb. I'm still coming up a bit short on reproducers with a few tests in a fresh Python 3.8.10 environment.

Just to verify a couple more things for your JupyterLab box install:
1. What version of `ipywidgets` Python package are you running?
2. What version of NodeJS are you running?
3. When running `!jupyter labextension list` on the JupyterLab box, does this show a good installation of `jupyterlab_widgets`(and if so, what version), ex. 
```
@jupyter-widgets/jupyterlab-manager v3.1.4 enabled OK (python, jupyterlab_widgets)
```
4. If possible, please provide the entire output of `pip list` from your Python environment.

> Does the widget run on a different port that needs to be tunneled too?

This shouldn't be an issue (I think), I've previously accessed a remote JupyterLab server w/graph-notebook and the widgets all rendered ok with everything served over port 8888.

**Comment by michaelnchin** [comment]
Closing due to >30 days of inactivity. Please re-open if there are further updates.
