### ISSUE TITLE
Sample notebook addition - molecular modeling blog

### ISSUE THREAD

**Issue by gkutchekAWS** [aws/graph-notebook#471]
**Community Note**
* Please use a 👍 reaction to provide a +1/vote. This helps the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Graph Notebook Version (and Graph Database and Version used if applicable)**

**Is your feature request related to a problem? Please describe.**
Submitting a request to add my sample notebook on molecular modeling to the repository of sample applications

**Describe the solution you'd like**
Approval and addition of the notebook file I have created to be added to the repository. Will be attached to upcoming blog publish

**Additional context**
Add any other context or screenshots about the feature request here. Describe any alternatives you've considered.

**Comment by michaelnchin** [comment]
Hi @gkutchekAWS ,

Thank you for the heads up. We greatly appreciate your interest in contributing to graph-notebook, and are looking forward to your sample notebook and blog post! 

Please feel free to submit a pull request for the new notebook whenever you are ready for a review.

**Comment by michaelnchin** [comment]
Closing in favor of #472.
