### ISSUE TITLE
[Doc accuracy] 

### ISSUE THREAD

**Issue by jlin83** [aws/graph-notebook#492]
**Community Note**
* Please use a 👍 reaction to provide a +1/vote. This helps the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Describe the bug**
I don't think the description in this [sample notebook](https://github.com/aws/graph-notebook/blob/main/src/graph_notebook/notebooks/02-Visualization/Grouping-and-Appearance-Customization-Gremlin.ipynb) is correct.  It notes that the group key values should be the list of values.  I couldn't get this to work.  However, something like this did:

```
%%graph_notebook_vis_options
{
  "groups": {
      "CA": {"color": "red"},
    "MX": {"shape": "image", 
               "image":"https://cdn.countryflags.com/thumbs/mexico/flag-round-250.png"},
    
    "US": {
      "shape": "icon",
      "icon": {
        "face": "FontAwesome",
        "code": "\uf072",
        "color": "#00FF00"
          }
      }
    }
}
```

 - OS: [e.g. Amazon Linux 2]
 - Browser: [e.g. Google Chrome]
 - Graph Notebook Version: [e.g. 3.7.3]
 - Graph Database & Version: [e.g., Amazon Neptune 1.2.1.0]

**To Reproduce**

**Expected behavior**

**Comment by michaelnchin** [comment]
Hi @jlin83, thank you for taking the time to open an issue!

For the example referenced, the group key values in the example `%%graph_notebook_vis_options` settings are in the correct format - however, this is somewhat specific to the example Gremlin query that follows it:

```
%%gremlin -p v,inv -g country
g.V().hasLabel('airport').has('code','CZM').out('route').path().by(valueMap())
```

In this query, we use the [valueMap](https://kelvinlawrence.net/book/Gremlin-Graph-Guide.html#vm) step to return the vertices in the path as maps containing their properties' key:value pairs. By default, valueMap returns property values as an element of a list, as it is possible for Gremlin vertex properties to have multiple values for a single key. 

Executing the above query, we can observe the list format property values in the path results returned:
```
path[{'country': ['MX'], 'code': ['CZM'], 'longest': [10165], ...
```

Prior to sending the Gremlin query results to the graph visualizer, property values are converted from raw format to string regardless of previous datatype. So, the list property value `['MX']` would become the literal string `"['MX']"`, and we would need to reference it as such inside "%%graph_notebook_vis_options". 

Of course, this is not applicable to all cases. If your Gremlin query uses a different step like `elementMap` that returns the property values as a single element, then you would want to reference them in the base format (i.e. just `"MX"`) when setting the visualization options.

**Comment by jlin83** [comment]
Thanks for the clarification!
