### ISSUE TITLE
[BUG] Javascript errors on Visualization

### ISSUE THREAD

**Issue by Mustahsan1** [aws/graph-notebook#508]
Facing following javascript errors in graph visualization tab:

```[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'ForceModel' from module 'graph_notebook_widgets'
Error: Script error for "graph_notebook_widgets"
http://requirejs.org/docs/errors.html#scripterror
    at makeError (https://test-connectivity-alexradu-rkl9.notebook.us-west-2.sagemaker.aws/static/nbclassic/components/requirejs/require.js?v=d37b48bb2137faa0ab98157e240c084dd5b1b5e74911723aa1d1f04c928c2a03dedf922d049e4815f7e5a369faa2e6b6a1000aae958b7953b5cc60411154f593:168:17)
    at HTMLScriptElement.onScriptError (https://test-connectivity-alexradu-rkl9.notebook.us-west-2.sagemaker.aws/static/nbclassic/components/requirejs/require.js?v=d37b48bb2137faa0ab98157e240c084dd5b1b5e74911723aa1d1f04c928c2a03dedf922d049e4815f7e5a369faa2e6b6a1000aae958b7953b5cc60411154f593:1735:36)
```

browser console: 
<img width="1427" alt="image" src="https://github.com/aws/graph-notebook/assets/28051325/cbb151a3-6277-4023-9d38-23bb94b26f7b">

`!jupyter labextension list` output:

```
JupyterLab v3.6.3
/home/ec2-user/anaconda3/envs/python3/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        jupyterlab-plotly v5.14.1 enabled OK
        graph_notebook_widgets v3.8.2 enabled OK (python, graph-notebook)
        @jupyter-widgets/jupyterlab-manager v5.0.7 enabled OK (python, jupyterlab_widgets)
```

**Comment by michaelnchin** [comment]
Hi @Mustahsan1, thank you for the issue submission!

Based on the `@jupyter-widgets/jupyterlab-manager` version, I assume you have `ipywidgets>=8.x` installed alongside graph-notebook. Unfortunately, this major version of ipywidgets is not compatible with graph-notebook at this time. 

I was able to reproduce the widgets script error when I had the following installed on a SageMaker Notebook Python 3.10 kernel:
```
Python:

ipywidgets                        8.0.7
widgetsnbextension                4.0.8

Labextensions:

jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
jupyterlab-plotly v5.14.1 enabled OK
graph_notebook_widgets v3.8.2 enabled OK (python, graph-notebook)
@jupyter-widgets/jupyterlab-manager v5.0.8 enabled OK (python, jupyterlab_widgets)
...
```

This should be remedied by downgrading your notebook to use `ipywidgets<=7.7.2` and `widgetsnbextension<=3.6.1`, per our [installation requirements](https://github.com/aws/graph-notebook/blob/main/requirements.txt).

**Comment by Mustahsan1** [comment]
Hi @michaelnchin I tried downgrading these dependencies, but still the error message is same as before.

**Comment by michaelnchin** [comment]
Quick check as I forgot to add to my original answer - did you also refresh the notebook kernel (Notebook top menu bar -> "Kernel" -> "Restart") and browser page following the downgrade?

**Comment by michaelnchin** [comment]
What is the result of rerunning `!jupyter labextension list` at the moment? It should now show
```
@jupyter-widgets/jupyterlab-manager v3.1.4 enabled OK (python, jupyterlab_widgets)
```

**Comment by Mustahsan1** [comment]
this is the current output:

```
JupyterLab v3.6.3
/home/ec2-user/anaconda3/envs/python3/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled OK (python, jupyterlab_pygments)
        jupyterlab-plotly v5.14.1 enabled OK
        graph_notebook_widgets v3.8.2 enabled OK (python, graph-notebook)
        @jupyter-widgets/jupyterlab-manager v3.1.4 enabled OK (python, jupyterlab_widgets)

```

**Comment by michaelnchin** [comment]
Thanks for confirming, something else in the existing notebook environment must be interfering with the widgets installation. Does the notebook's `jupyter.log` in CloudWatch provide any additional information around the same time that the widgets error occurs?

**Comment by michaelnchin** [comment]
If it's possible - would you be willing to use a separate Jupyter kernel on your SageMaker notebook, to clean install and run graph-notebook on? 

Setup can be automated in a similar way to the managed [Neptune Notebooks](https://docs.aws.amazon.com/neptune/latest/userguide/graph-notebooks.html#graph-notebooks-workbench) service, by modifying the following settings on your SageMaker notebook: 

1. Change on-start Lifecycle Configuration to include:
```
#!/bin/bash
 
sudo -u ec2-user -i <<'EOF'
 
echo "export GRAPH_NOTEBOOK_AUTH_MODE=[IAM|DEFAULT]" >> ~/.bashrc
echo "export GRAPH_NOTEBOOK_HOST=[NEPTUNE_WRITER_ENDPOINT]" >> ~/.bashrc
echo "export GRAPH_NOTEBOOK_PORT=8182" >> ~/.bashrc
echo "export NEPTUNE_LOAD_FROM_S3_ROLE_ARN=" >> ~/.bashrc
echo "export AWS_REGION=us-west-2" >> ~/.bashrc
 
aws s3 cp s3://aws-neptune-notebook-us-west-2/graph_notebook.tar.gz /tmp/graph_notebook.tar.gz
rm -rf /tmp/graph_notebook
tar -zxvf /tmp/graph_notebook.tar.gz -C /tmp
/tmp/graph_notebook/install.sh
 
EOF
```

2. Add permissions to read `s3://aws-neptune-notebook-us-west-2` to your notebook's IAM role policy, ex.
```
    {
      "Effect": "Allow",
      "Action": [
        "s3:GetObject",
        "s3:ListBucket"
      ],
      "Resource": [
        "arn:aws:s3:::aws-neptune-notebook-us-west-2",
        "arn:aws:s3:::aws-neptune-notebook-us-west-2/*"
      ]
    }
```

If you're unsure whether your notebook is already configured to access the Neptune cluster, also check that:

1. The notebook's network settings (VPC, subnet, security group) match the Neptune db

2. IAM role policy should include a statement granting actions on the Neptune db:
```
    {
      "Effect": "Allow",
      "Action": "neptune-db:*",
      "Resource": [
        "arn:aws:neptune-db:us-west-2:(AWS account ID):(Neptune resource ID)/*"
      ]
    }
```

After following the above and rebooting your SageMaker notebook instance, you should see a new "Python 3" Jupyter kernel where graph-notebook is set up and ready to query your Neptune cluster.

**Comment by Mustahsan1** [comment]
Hi @michaelnchin , can you please let us know where we can find graph_notebook.tar.gz file from?

**Comment by triggan** [comment]
It is referenced in the Lifecycle Configuration script in the last response from @michaelnchin - 
```
s3://aws-neptune-notebook-us-west-2/graph_notebook.tar.gz
```
Be sure to change the region to whichever region you're operating in.

**Comment by Mustahsan1** [comment]
thanks! It solved the issue 🙇

**Comment by timurta123** [comment]
If you a gov cloud user, this bucket is not accessible as it is on commercial partition. As a workaround you can manually download it into your own account s3 bucket and do the rest. It would be good if you also maintain a bucket on gov cloud side for future use and automatic updated
