### ISSUE TITLE
Support for virtuoso sparql endpoint

### ISSUE THREAD

**Issue by Jefwillems** [aws/graph-notebook#51]
**Is your feature request related to a problem? Please describe.**
I've been trying to have graph-notebook connect to a virtuoso sparql endpoint, without success. 

**Describe the solution you'd like**
Support for virtuoso sparql endpoints. Or, if already possible, documentation about connection setup.

**Comment by beebs-systap** [comment]
@Jefwillems Can you describe what you tried and how it failed?

**Comment by austinkline** [comment]
@Jefwillems can we please get the contents of the configuration you are trying to use to connect to your desired endpoint? You can obtain this by running:
```
%graph_notebook_config
```

**Comment by john-roj** [comment]
graph-notebook expects the sparql endpoint somehow hardcoded for neptune, it needs  to end in `/sparql`  [according to the code](https://github.com/aws/graph-notebook/blob/main/src/graph_notebook/request_param_generator/sparql_request_generator.py#L17)  luckily the configuration can be changed to something like:

```
%%graph_notebook_config
{
  "host": "my-host",
  "port": "3030/base-ontologies",
  "auth_mode": "DEFAULT",
  "iam_credentials_provider_type": "ROLE",
  "load_from_s3_arn": "",
  "ssl": false,
  "aws_region": "us-east-1"
}
```
This config will try to hit a sparql endpoint in http://myhost:3030/base-ontologies/sparql
notice the `ssl:false` so it is not https... the restriction for this notebook is that the virtuoso endpoint needs to end in `/sparql`

This is more of a workaround that seems to work, but perhaps the config could be extended so it is not so neptune.

**Comment by beebs-systap** [comment]
I believe that https://github.com/aws/graph-notebook/pull/49 will address this.

**Comment by Jefwillems** [comment]
> I believe that https://github.com/aws/graph-notebook/pull/49 will address this.

Thanks, i will investigate further. Didn't have time until now.

Closing for now
