### ISSUE TITLE
[BUG] Unable to Synchronize Graph

### ISSUE THREAD

**Issue by RonLek** [aws/graph-notebook#539]
**Community Note**
* Please use a 👍 reaction to provide a +1/vote. This helps the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Describe the bug**
I'm trying to visualize data from my Neptune DB using graph-explorer. I'm running graph-explorer in an EC2 instance within the same VPC as my Neptune cluster and creating an SSH tunnel from my local to port `8182` of this instance for connection. I can verify the connection by getting a response from `https://<NEPTUNE_ENDPOINT>:8182/status` from my browser.

However, the synchronization fails. The Network tab looks like the following

<img width="1348" alt="image" src="https://github.com/aws/graph-notebook/assets/28918901/2ee4c319-fa45-42ed-af4e-d7c05d429a35">

The first gremlin request gets a correct response but the second one fails with a `400`. Additionally, the `summary` request fails due to a CORS error. Connectivity to the Neptune cluster is not a problem since the first gremlin request succeeds.

My graph has approximately 3,500 nodes and edges which I presume should not be large to cause timeouts.

 - OS: Amazon Linux 2
 - Browser: Google Chrome
 - Graph Notebook Version: Built from current source
 - Graph Database & Version: Amazon Neptune 1.2.1.0

**Expected behavior**
A successful synchronization of the data.

**Comment by RonLek** [comment]
@michaelnchin @triggan would you know how to go about this?

**Comment by triggan** [comment]
Is there any reason why you're looking to use an SSH tunnel versus the built-in proxy of Graph Explorer?

What are the details of the 400 error that is coming back on the subsequent requests?

**Comment by triggan** [comment]
Just realized you posted this in the graph-notebook repo.  Graph Explorer is a different project:  https://github.com/aws/graph-explorer

**Comment by RonLek** [comment]
My bad, had multiple tabs open. Opening this in that repo. Thanks.
