### ISSUE TITLE
[BUG] Seems like this is broken when used against latest tinkerpop

### ISSUE THREAD

**Issue by lyndonbauto** [aws/graph-notebook#548]
I am trying to use the graph-notebook project, my project previously worked. I updated Aerospike graph to the latest version of tinkerpop and with it the serializers were updated. 

Trying to run any %%gremlin  now results in an error of 

```
[WARN] o.a.t.g.s.h.WsGremlinBinaryRequestDecoder - Gremlin Server is not configured with a serializer for the requested mime type [application/vnd.gremlin-v3.0+json] - using org.apache.tinkerpop.gremlin.util.ser.GraphBinaryMessageSerializerV1 by default
[WARN] o.a.t.g.s.h.WsGremlinBinaryRequestDecoder - Serialization error while decoding request
org.apache.tinkerpop.gremlin.util.ser.SerializationException: The most significant bit should be set according to the format
        at org.apache.tinkerpop.gremlin.util.ser.binary.RequestMessageSerializer.readValue(RequestMessageSerializer.java:45)
```

which is a mismatch on the serializer. I can't seem to find a way to change the serializer in this magic cell. Is there a workaround for this?

 - OS: Amazon Linux 2 docker
 - Browser: Brave
 - Graph Notebook Version: latest
 - Graph Database & Version: Aerospike Graph using latest TinkerPop

**To Reproduce**
Run any gremlin command in the %% gremlin cell

**Expected behavior**
It used to just run the gremlin, I am surprised we can't pick a serializer in the notebook tho, this seems like a reasonable feature to consider.

**Comment by michaelnchin** [comment]
Hi @lyndonbauto,

For any non-Neptune endpoint, you can configure the Gremlin serializer via the `message_serializer` field in the notebook configuration, for example:

```
%%graph_notebook_config
{
  "host": "localhost",
  "port": 8182,
  "ssl": false,
  "gremlin": {
    "message_serializer": "graphbinary"
  }
}
```

If `message_serializer` is not specified, GraphSON V3 will be used by default.

**Comment by lyndonbauto** [comment]
Ah that works. Okay well heads up the default will break when using 3.7.0, thanks for the quick reply!
