### ISSUE TITLE
JupyterLabs support

### ISSUE THREAD

**Issue by austinkline** [aws/graph-notebook#55]
**Is your feature request related to a problem? Please describe.**
Related to #54 
Query outputs are not rendered properly in JupyterLabs.

**Describe the solution you'd like**
All rendered widgets and magic commands which work in Notebooks should also work in labs. Ideally the extension would load automatically like it does in notebooks.

**Additional context**
Labs screenshot:
![image](https://user-images.githubusercontent.com/8711160/103672471-340a1580-4f31-11eb-9382-3875c8d9f584.png)

Note that there is not a tab output widget like there should be, and the table that is visible (you can see the first column) is not the fully formed Datatable which we use.

**Comment by mpgreg** [comment]
+1.  Active use-cases limited by need to move back and forth between SageMaker NB instances for Neptune and SageMaker Studio.

**Comment by jacekko** [comment]
> +1. Active use-cases limited by need to move back and forth between SageMaker NB instances for Neptune and SageMaker Studio.

+ 1

**Comment by stechr** [comment]
+1

**Comment by vishnukraj1111** [comment]
+1
