### ISSUE TITLE
[BUG] TinkerPop tutorial commands not working in %%gremlin

### ISSUE THREAD

**Issue by adhalanay** [aws/graph-notebook#563]
**Community Note**
* Please use a 👍 reaction to provide a +1/vote. This helps the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Describe the bug**
A clear and concise description of what the bug is and the environment/context.

 - OS: [Linux 5.15.146.1-microsoft-standard-WSL2]
 - Browser: [Mozilla Firefox]
 - Graph Notebook Version: [4.1.0]
 - Graph Database & Version: [Gremlin Server 3.7.1]

**To Reproduce**
1. Run `%% gremlin graph = TinkerFactory.createModern() g = traversal().withEmbedded(graph)`
2. Got the error `{'error': GremlinServerError('599: Error during serialization: Could not find a type identifier for the class : class org.apache.tinkerpop.gremlin.tinkergraph.process.traversal.strategy.optimization.TinkerGraphCountStrategy. Make sure the value to serialize has a type identifier registered for its class. (through reference chain: org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversalSource["strategies"])')}`

**Expected behavior**
Console with result

When I try to replicate the example from Getting started with ApacheTikerpop (https://tinkerpop.apache.org/docs/current/tutorials/getting-started/) I receive the previous error. The problem seems to be in the second query.

**Comment by michaelnchin** [comment]
Hi @adhalanay, thank you for submitting an issue!

> `%% gremlin graph = TinkerFactory.createModern() g = traversal().withEmbedded(graph)`

Some initial clarification - the TinkerPop tutorial examples referenced are in Gremlin Groovy (Java-based) syntax. Groovy is just one of many [Gremlin Language Variants](https://tinkerpop.apache.org/docs/3.7.1/reference/#gremlin-drivers-variants) available for use with TinkerPop. Graph-notebook is Python based, and therefore instead utilizes the [Gremlin Python](https://github.com/apache/tinkerpop/tree/master/gremlin-python/src/main/python) GLV, which may not work with certain Groovy commands/syntax.

When using the `%%gremlin` magic, it's not necessary to manually generate a traversal source, as this is handled under the covers by the [Gremlin Python Client](https://github.com/apache/tinkerpop/blob/master/gremlin-python/src/main/python/gremlin_python/driver/client.py) responsible for creating the websocket connection to Gremlin Server, as seen [here](https://github.com/aws/graph-notebook/blob/main/src/graph_notebook/neptune/client.py#L323). The traversal source is set to `g` by default, but if desired, you can change this via the `gremlin` -> `traversal_source` field in `%%graph_notebook_config`. Once you're happy with this configuration, you can start submitting queries directly via `%%gremlin`, or batch loading data using `%seed`.

I would recommend checking out our tutorial for setting up graph-notebook with Gremlin Server, which has additional instructions and considerations for initial setup: https://github.com/aws/graph-notebook/tree/main/additional-databases/gremlin-server.

**Comment by adhalanay** [comment]
@michaelnchin Thank you for you reply. So if I understand correctly after instantiating a graph `g` is the corresponding traversal. But when I try a query like `g.V()` I get an empty reply instead of the six vertices.

As a side note a similar query works very good with JanusGraph.

**Comment by michaelnchin** [comment]
The new graph you're instantiating via the `graph = TinkerFactory.createModern()` command exists in memory, but is not assigned to or accessible via the traversal source `g`, due to the second command `g = traversal().withEmbedded(graph)` failing to run. 

Since it hasn't been re-assigned to a different graph, `g` instead remains as the default traversal source for the empty default graph created by Gremlin Server - this empty graph is where your queries are currently being routed to.

TBH, the `%%gremlin` magic is only intended for running straight Gremlin queries. Other TinkerPop actions would be better executed via external means, like Gremlin Console, or even writing Gremlin Python code in the same Jupyter instance where you're using graph-notebook.

**Comment by adhalanay** [comment]
So if I understand correctly one should use Gremlin Python instead of Gremlin Groovy. I think it is safe to close the bug now.

**Comment by michaelnchin** [comment]
Thanks @adhalanay - please feel free to re-open if you have additional questions 👍
