### ISSUE TITLE
Documentation for specifying sparql paths on Blazegraph

### ISSUE THREAD

**Issue by wdduncan** [aws/graph-notebook#61]
Does PR https://github.com/aws/graph-notebook/pull/49 fix issues #39 and #45 ?
If so, can you please post documentation? I've tried:

```
%%graph_notebook_config
{
  "host": "http://kg-hub-rdf.berkeleybop.io",
  "port": 80,
  "auth_mode": "DEFAULT",
  "iam_credentials_provider_type": "ROLE",
  "load_from_s3_arn": "",
  "ssl": false,
  "aws_region": "us-east-1"
  "sparql": {
       "blazegraph/sparql"
   }
}
```
and
```
%%graph_notebook_config
{
  "host": "http://kg-hub-rdf.berkeleybop.io",
  "port": 80,
  "auth_mode": "DEFAULT",
  "iam_credentials_provider_type": "ROLE",
  "load_from_s3_arn": "",
  "ssl": false,
  "aws_region": "us-east-1"
  "sparql_path": "blazegraph/sparql"
}
```
But I receive syntax errors.

**Comment by austinkline** [comment]
Hi @wdduncan, can you please provide a screenshot of the syntax error you are receiving? It would also be helpful to know what release of notebooks you are running on. You can obtain version information by running `%graph_notebook_version`

As for an immediate suggestion, give the following a try:

```
%%graph_notebook_config
{
  "host": "http://kg-hub-rdf.berkeleybop.io",
  "port": 80,
  "auth_mode": "DEFAULT",
  "iam_credentials_provider_type": "ROLE",
  "load_from_s3_arn": "",
  "ssl": false,
  "aws_region": "us-east-1"
  "sparql": {
       "blazegraph"
   }
}
```

**Comment by fils** [comment]
@austinkline 

I use  
```%%graph_notebook_config
{
  "host": "https://foo.org.org",
  "port": 80,
  "auth_mode": "DEFAULT",
  "iam_credentials_provider_type": "ROLE",
  "load_from_s3_arn": "",
  "ssl": true,
  "aws_region": "us-east-1",
  "sparql": {
      "nabu"
   }
}
```

and get

```{'error': JSONDecodeError("Expecting ':' delimiter: line 11 column 4 (char 223)")}
```

**Comment by austinkline** [comment]
My mistake, left out a json key. See below for the corrected config:

```
%%graph_notebook_config

{
  "host": "https://foo.org.org",
  "port": 80,
  "auth_mode": "DEFAULT",
  "iam_credentials_provider_type": "ROLE",
  "load_from_s3_arn": "",
  "ssl": true,
  "aws_region": "us-east-1",
  "sparql": {
      "endpoint_prefix": "nabu"
   }
}
```

See the screenshot below, note that the endpoint constructed is `foo.org.org:80/nabu/sparql`

![image](https://user-images.githubusercontent.com/8711160/107436719-c8dcd180-6ae2-11eb-9bfa-9f28c84d7911.png)

**Comment by fils** [comment]
Thank you..   using the config

```
...
 "sparql": {
      "endpoint_prefix": "blazegraph/namespace/nabu/sparql"
   }
...
```

now works for me..  Looking forward to using this with my team!

**Comment by wdduncan** [comment]
@austinkline I'm using `2.0.7`

The endpoint I am trying to connect to is `http://kg-hub-rdf.berkeleybop.io/blazegraph/sparql`. I can connect to the endpoint and query using `SPARQLWrapper`. E.g.:
``` python
from SPARQLWrapper import SPARQLWrapper, JSON

sparql_service_url = "http://kg-hub-rdf.berkeleybop.io/blazegraph/sparql"
sparql_query = "select * where { ?s ?p ?o} limit 10"

sparql = SPARQLWrapper(sparql_service_url)
sparql.setQuery(sparql_query)
sparql.setReturnFormat(JSON)

result = sparql.query().convert()
```
However, I still can't connect to the endpoint using `graph_notebook`. See screenshots.

![image](https://user-images.githubusercontent.com/3186638/107648718-a49c0480-6c4a-11eb-9155-705ac0afb886.png)

![image](https://user-images.githubusercontent.com/3186638/107648784-b67da780-6c4a-11eb-98a6-78f1cb6723e3.png)

**Comment by beebs-systap** [comment]
@wdduncan Can you try removing the `/sparql` from your endpoint_prefix?

```
"endpoint_prefix" : "blazegraph"
```

**Comment by wdduncan** [comment]
@beebs-systap Unfortunately, that fails too :(

![image](https://user-images.githubusercontent.com/3186638/107670377-ab357680-6c60-11eb-8836-d1d7473176ba.png)

**Comment by wdduncan** [comment]
As a follow up, here is the link to the public webpage you can use to run a query: http://kg-hub-rdf.berkeleybop.io/blazegraph/#query

For the query `select * where {?s ?p ?o} limit 10`, I used Chrome's network inspector to view the traffic.
![image](https://user-images.githubusercontent.com/3186638/107674548-11bc9380-6c65-11eb-9eeb-23eb120859dc.png)

I modified the `graph-notebook` config to be `"endpoint_prefix": "blazegraph/namespace/kb"`, but still received an error.
![image](https://user-images.githubusercontent.com/3186638/107674748-492b4000-6c65-11eb-8e9a-904ccbed4082.png)

**Comment by austinkline** [comment]
@wdduncan give this a try:
```
%%graph_notebook_config

{
  "host": "kg-hub-rdf.berkeleybop.io",
  "port": 80,
  "auth_mode": "DEFAULT",
  "iam_credentials_provider_type": "ROLE",
  "load_from_s3_arn": "",
  "ssl": false,
  "aws_region": "us-east-1",
  "sparql": {
      "endpoint_prefix": "blazegraph"
   }
}
```

![image](https://user-images.githubusercontent.com/8711160/107697547-3c5c1b80-6c68-11eb-8597-a75bab82839f.png)

**Comment by wdduncan** [comment]
@austinkline SUCCESS! THANKS :)

But how did you get it to work? Your config looks the one I posted for @beebs-systap in
https://github.com/aws/graph-notebook/issues/61#issuecomment-777642336

Sorry ... if I'm missing something obvious :(

**Comment by austinkline** [comment]
I removed the `http://` from the beginning, we build the url for a query base on host, port, and your ssl setting

**Comment by wdduncan** [comment]
DOH!!! How did I miss that :)   
Thanks
