### ISSUE TITLE
[BUG]  Issue with Graph Rendering in Gremlin Queries on JupyterLab

### ISSUE THREAD

**Issue by amansharif** [aws/graph-notebook#696]
I am encountering an issue where my Gremlin queries do not render as graphs. I'm unsure if this is related to the Graph Notebook widget, but it does not seem to be functioning as expected in my environment. I am running JupyterLab via JupyterHub, which is deployed on Kubernetes.

Here are the details of my environment:

- OS: Linux SMP Debian 5.10.223-1 (2024-08-10) x86_64 x86_64 x86_64 GNU/Linux
- Browser: Google Chrome
- Graph Notebook Version: 4.5.2
- Graph Database & Version: JanusGraph 1.0.0
- Python Version: 3.9.13

I have attached relevant screenshots at the end for your reference. I would greatly appreciate your guidance on resolving this issue.

Here's the relevant screenshots

![image](https://github.com/user-attachments/assets/1db7e90e-f00b-40c2-9693-52b8afdc7fd4)
![image](https://github.com/user-attachments/assets/94f359c8-14f9-4f5c-bbe5-329e9d011087)

Thank you so much for your time and support!

**Comment by michaelnchin** [comment]
Hi @amansharif, thank you for submitting an issue!

I tried manually installed your Jupyter package versions a Python 3.9.19 environment with `graph-notebook`. This resulted in an extensions warning when launching JupyterLab:

```
3c22fb5e1f47:graph-notebook chnmch$ python -m graph_notebook.start_jupyterlab --jupyter-dir ~/notebook/destination/dir
[W 2024-09-20 20:57:49.213 ServerApp] jupyter_server_terminals | error adding extension (enabled: True): Jupyter Server Terminals requires Jupyter Server 2.0+
    Traceback (most recent call last):
      File "/Users/chnmch/.pyenv/versions/3.9.13/envs/test-3.9.13/lib/python3.9/site-packages/jupyter_server/extension/manager.py", line 320, in add_extension
        ...
    RuntimeError: Jupyter Server Terminals requires Jupyter Server 2.0+
```

Installing both JupyterLab 3 and graph-notebook fresh in a different Python 3.9.19 env did not did not give me any issues. For comparison, this was the resulting Jupyter packages list:
```
3c22fb5e1f47:graph-notebook chnmch$ jupyter --version
Selected Jupyter core packages...
IPython          : 8.10.0
ipykernel        : 5.3.4
ipywidgets       : 7.7.2
jupyter_client   : 7.4.9
jupyter_core     : 5.7.2
jupyter_server   : 2.14.2
jupyterlab       : 3.6.8
nbclient         : 0.7.3
nbconvert        : 7.2.8
nbformat         : 5.10.4
notebook         : 6.5.7
qtconsole        : 5.6.0
traitlets        : 5.14.3

```

It looks like some of the older Jupyter dependencies in your environment may be preventing the widgets extensions from loading properly. Please try upgrading to the latest versions supported by Python 3.9 and JupyterLab 3, and see if it helps.

**Comment by michaelnchin** [comment]
Closing due to 30 days of inactivity - please re-open if there are further updates.
