### ISSUE TITLE
[BUG] I can't connect to NeptuneDB even after setting SSH tunnel to NeptuneDB

### ISSUE THREAD

**Issue by ImBharathwaj** [aws/graph-notebook#709]
**Community Note**
* Please use a 👍 reaction to provide a +1/vote. This helps the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Describe the bug**
I couldn't connect with `NeptuneDB` with local python. Even after setting-up the SSH tunnel using below command
`ssh -L port_number:neptune_db_server_url:neptune_db_port bastion_config`

I am getting this error when connecting local python with `NeptuneDB` using proper credentials & attributes

`{'errorMessage': "HTTPSConnectionPool(host='dev-adp-graph.cluster-cru2jn55wrxr.us-east-1.neptune.amazonaws.com', port=8182): Max retries exceeded with url: /loader (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x00000200BBBA5130>, 'Connection to dev-adp-graph.cluster-cru2jn55wrxr.us-east-1.neptune.amazonaws.com timed out. (connect timeout=None)'))", 'stackTrace': 'NoneType: None\n'}`

**Can anyone give solution to this problem?**

**Comment by triggan** [comment]
Is the security group for your cluster configured to allow traffic from the bastion host?  If you connect to the bastion and attempt a `curl https://<neptune-endpoint>:<neptune-port>/status` does this return a response?  These timeout issues are generally related to network or security misconfiguration.  So I would suggest starting there.

**Comment by ImBharathwaj** [comment]
With the same bastion server I connected AWS MWAA (Airflow) and its working as expected.
But when it comes to NeptuneDB its not working.

I checked by running the same command 
`curl https://<neptune-endpoint>:<neptune-port>/status` 
The outcome is
![image](https://github.com/user-attachments/assets/5971fca2-a1e4-4cdf-81eb-f176ef5d3dec)

But bastion tunnel still in connection

**Comment by triggan** [comment]
It is likely a security group configuration issue, then.  If your bastion is working when connecting to MWAA and MWAA workflows are working when connecting to Neptune, then the security group is likely configured to allow connections from the MWAA workflows and not from your bastion host.  So you'll need to adjust the configuration of the security group to allow traffic from your bastion host (as the bastion host will also be the source when connecting via an SSH tunnel).

**Comment by ImBharathwaj** [comment]
Okay, Thanks for the Info @triggan
