### ISSUE TITLE
[BUG] Broken Graph visualization in Jupyterlab

### ISSUE THREAD

**Issue by vgrangep** [aws/graph-notebook#714]
**Community Note**
* Please use a 👍 reaction to provide a +1/vote. This helps the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Describe the bug**
Visualization of the gremlins graph query fails in JupyterLab. there are Js errors in the Console.

- OS: macOS Sonoma 14.6.1
- Chip: M1 max
- Browser: Chrome
- Graph Notebook Version: graph-notebook 4.6.1
- Graph Database & Version: Neptune 1.2.0.2
--

**To Reproduce**
Using the main branch of the project: [https://github.com/aws/graph-notebook](https://github.com/aws/graph-notebook )
Following the install procedure:
- using Python 3.9.10
- manual creation of a virtualenv and installation of dependencies using the provided requirements file
`pip install -r requirements.txt`
- install of the graph-notebook package with pip
`pip install graph-notebook`
- install of jupyter lab with version constraints using the provided command:
`pip install "jupyterlab>=3,<4"`

- connect to the database and run a gremlin query: 
```
%%gremlin
g.V().limit(10).path().by(elementMap())
```
Gremlin queries are processed correctly
![03ecdcf0-f38c-4455-8541-144624876d6d](https://github.com/user-attachments/assets/b8593e46-15a3-4bac-a303-4a8396581f86)
But visualization is missing
![ec3321bb-cf44-494d-a637-4ce3743396e0](https://github.com/user-attachments/assets/c1e4565f-36dc-464e-b0a0-4d16b64f0b2f)
- js error in the console:
![90b6ecd7-5ba1-4769-a664-d16634f6c2df](https://github.com/user-attachments/assets/d0e4a7ec-834c-4a02-89f4-ce94a181317e)

**Expected behavior**
A visual representation the graph subquery as it used to be displayed
![Screenshot 2024-11-01 at 4 00 47 PM](https://github.com/user-attachments/assets/bed9cc48-be2c-4ffa-a7dc-f4a16817ebdc)

**Comment by michaelnchin** [comment]
@vgrangep, thank you for the bug report!

I was able to reproduce this locally. It looks like the most recent version of the `jupyterlab-widgets` chain dependency [1.1.11](https://pypi.org/project/jupyterlab-widgets/1.1.11/)) expects JupyterLab 4, and breaks the widget. 

We'll include a version pin fix in the next release. In meantime, please include the following in your installation process:
```
pip install "jupyterlab-widgets<=1.1.10"
```

**Comment by vgrangep** [comment]
This is working fine. Thanks for your help !
