### ISSUE TITLE
Add option to allow the physics simulation duration to be set by the user

### ISSUE THREAD

**Issue by krlawrence** [aws/graph-notebook#74]
Today the Physics simulation is hard coded to never run for longer than 1.5 seconds (https://github.com/aws/graph-notebook/blob/main/src/graph_notebook/widgets/src/force_widget.ts#L142). 

This makes sense in a lot of cases as simulations can run for a very long time otherwise and it needs to be stopped at some point. However, some simulations really do need to run for longer (say 30 seconds or a minute) to achieve a pleasant looking result - especially when more than a few nodes and edges are part of the simulation. It would be nice to expose a way for a user to adjust the maximum. simulation duration. Today you can jiggle vertices with the mouse pointer to get some additional computation but it is not sufficient.

**Comment by bechbd** [comment]
This would also be good to allow for disabling the physics after this time has completed so that nodes could be moved around without affecting the position of other nodes.
