### ISSUE TITLE
Error installing widgets nbextensions

### ISSUE THREAD

**Issue by rnphilp** [aws/graph-notebook#83]
Hi. When running through the setup I hit an error while trying to install the widget nbextensions.

I'm running the Jupyter notebook in a local env using Python 3.6.12 and graph-notebook version 2.0.9.

Steps followed:
```
python -m venv env
source env/bin/activate
pip install -r requirements.txt

jupyter nbextension install --py --sys-prefix graph_notebook.widgets
```

requirements.txt
```
notebook==5.7.10
tornado==4.5.3
graph-notebook==2.0.9
```

Running the last command `jupyter nbextension install --py --sys-prefix graph_notebook.widgets` returns the error:
```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/{user}/repos/graph-notebook/env/lib/python3.6/site-packages/graph_notebook/widgets/nbextension/static'
```

running `which jupyter` returns `/Users/{user}/repos/graph-notebook/env/bin/jupyter`, so its running in the local environment.

Any ideas?
Thanks.

**Comment by austinkline** [comment]
Thanks for reporting @rnphilp, I was able to reproduce:

```
pyenv global 3.6.12
python -m venv /tmp/venv
source /tmp/venv/bin/activate

pip install -r requirements.txt
pip install graph-notebook

jupyter nbextension install --py --sys-prefix graph_notebook.widgets
```

Gets me to:
```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/venv/lib/python3.6/site-packages/graph_notebook/widgets/nbextension/static'
```

I downloaded the release whl for 2.0.9 and can indeed see that the widgets directory is missing some content. We will cut a release to `2.0.10` to fix this and let you know when it is done.

**Comment by rnphilp** [comment]
That's fixed it. Thanks!

**Comment by austinkline** [comment]
Beat me to it! Glad this works, thank again for reporting the issue
