### ISSUE TITLE
[BUG] Graph tab not displaying

### ISSUE THREAD

**Issue by rnphilp** [aws/graph-notebook#86]
**Describe the bug**
When running gremlin queries, only the console tab renders. The graph tab is missing.

**To Reproduce**
I'm running the Jupyter notebook in a local env using Python 3.6.12 and graph-notebook version 2.0.10.
```
python -m venv env
source env/bin/activate
pip install -r requirements.txt

jupyter nbextension install --py --sys-prefix graph_notebook.widgets
jupyter nbextension enable  --py --sys-prefix graph_notebook.widgets
python -m graph_notebook.static_resources.install
python -m graph_notebook.nbextensions.install

jupyter notebook ./index.ipynb
```

requirements.txt:
```
notebook==5.7.10
tornado==4.5.3
graph-notebook==2.0.10
```

**Expected behavior**
The graph tab renders and displays a visual of the graph.

**Screenshots**
![image](https://user-images.githubusercontent.com/30417054/111711111-f257ee00-8842-11eb-99ba-5ef9e2d09d1b.png)

**Desktop (please complete the following information):**
 - OS: iOS 10.14.6
 - Browser: chrome
 - Version: 88

**Additional context**
I do get a dependency clash when running pip install:
```
graph-notebook 2.0.10 has requirement Jinja2==2.10.1, but you'll have jinja2 2.11.3 which is incompatible.
```
And also the following errors in the console when running the notebook:
```
Could not open static file ''
404 GET /static/components/react/react-dom.production.min.js (::1) 16.75ms referer=http://localhost:8888/tree?token={token}
404 GET /static/components/react/react-dom.production.min.js (::1) 1.76ms referer=http://localhost:8888/tree?token={token}
```

I've also tried running 
```
jupyter nbextension enable graph_notebook.nbextensions --py --sys-prefix
```
after running 
```
python -m graph_notebook.nbextensions.install
```
Not sure if it's needed but didn't have any effect on the issue.

**Comment by austinkline** [comment]
Hey @rnphilp, regarding the graph tab not showing up, the only queries for Gremlin that will result in a rendered graph tab are paths, I would suggest checking out our tutorial notebooks for a walkthrough of how that works. The gremlin visualization notebooks can be found [here](https://github.com/aws/graph-notebook/tree/main/src/graph_notebook/notebooks/02-Visualization)

If you want to install these starter notebooks for use in your own jupyter server, you can run the following to copy them to your own directory:

```
# copy premade starter notebooks
python -m graph_notebook.notebooks.install --destination ~/notebook/destination/dir  

# start jupyter
jupyter notebook ~/notebook/destination/dir
```

**Comment by rnphilp** [comment]
Thanks @austinkline! Yes, my fault for not going reading through them. The examples are great!
