### ISSUE TITLE
[BUG] Specifying the GroupBy Field when just a vertex is returned

### ISSUE THREAD

**Issue by bechbd** [aws/graph-notebook#93]
**Describe the bug**
The group by field is not working when the value being returned is a vertex.  I am unable to group by id.

**To Reproduce**
```
%%gremlin -g id

g.V().path()
```
**Expected behavior**
I would have expected that this would give a different color to each node

**Comment by michaelnchin** [comment]
This bug is now fixed as of Release 2.1.2.
