### ISSUE TITLE
Notebook variables in Gremlin cell magic

### ISSUE THREAD

**Issue by spiermar** [aws/graph-notebook#98]
**Is your feature request related to a problem? Please describe.**
Related to a limitation. Often a value defined in the Python notebook needs to be used in a query, but today that is not possible, and the value needs to be copied and pasted in the cell query.

**Describe the solution you'd like**
A way of referencing a variable in the cell magic. Eg.: `${variable_name}`

**Describe alternatives you've considered**
Not ideal, but string formatting a query and executing the query string.
```
query = f'g.V({variable_1})'
res = gremlin.execute(query)
```

**Additional context**
SQL and Spark notebook magics provide a similar feature.

**Comment by austinkline** [comment]
Thanks @spiermar for the request! This is something we think would benefit all our cell magics. The most likely syntax we'd see some through from it is to enable some sort of variable enbedding with the syntax `${foo}`, so then for a gremlin query we may see:

```
foo = 'airport'
```

```
%%gremlin

g.V().hasLabel('${foo}')...
```

**Comment by spiermar** [comment]
Thank you @austinkline! That's exactly the syntax our SQL and Spark cell magics use.

**Comment by michaelnchin** [comment]
Variable injection in the requested format was added in PR #113.

**Comment by spiermar** [comment]
Great! Thank you @michaelnchin and @austinkline!
